apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "clothing-model"
spec:
  predictor:
    serviceAccountName: sa
    tensorflow:
      storageUri: "s3://mlbookcamp-models/clothing-model"
