apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "clothing-model"
spec:
  predictor:
    serviceAccountName: sa
    tensorflow:
      storageUri: "s3://mlbookcamp-models/clothing-model"
  transformer:
    containers:
      - image: "agrigorev/kfserving-keras-transformer:0.0.1"
        name: user-container
        env:
          - name: MODEL_INPUT_SIZE
            value: "299,299"
          - name: KERAS_MODEL_NAME
            value: "xception"
          - name: MODEL_LABELS
            value: "dress,hat,longsleeve,outwear,pants,shirt,shoes,shorts,skirt,t-shirt"