apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
    serving.kserve.io/s3-endpoint: s3.eu-west-1.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-verifyssl: "1"
    serving.kserve.io/s3-region: eu-west-1
    serving.kserve.io/s3-useanoncredential: "false"
type: Opaque
data:
  # echo -ne "AKIAxxx" | base64
  AWS_ACCESS_KEY_ID: INSERT_BAS64_KEY_HERE
  AWS_SECRET_ACCESS_KEY: INSERT_BASE64_SECRET_HERE
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret